version: 2
jobs:

  build:
    branches:
      only:
      - develop
      - master

    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      BETA_FASTLANE_LANE: allBetas
      RELEASE_FASTLANE_LANE: allReleases

    steps:
    - checkout

    - restore_cache:
        key: 1-gems-{{ checksum "Gemfile.lock" }}

    - run: bundle check || bundle install --path vendor/bundle

    - save_cache:
        key: 1-gems-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

    - run: echo $ENCODED_KEYSTORE | base64 --decode > keystore.jks

    - run: echo 'export KEYSTORE=${HOME}/project/keystore.jks' >> $BASH_ENV

    - run:
        name: fastlane
        command: |
          export fastlane= if [[$CIRCLE_BRANCH -eq "develop"]] then "bundle exec fastlane $BETA_FASTLANE_LANE" else "bundle exec fastlane $RELEASE_FASTLANE_LANE" fi
          echo $fastlane

    - store_artifacts:
        path: output

    - store_test_results:
        path: output/scan