default_platform(:android)

import("Fastrelease")
import("Fastbeta")

ENV["SLACK_URL"] = "https://hooks.slack.com/services/yourincomingwebhookurl"


    lane :test do |values|
         gradle(
                task: 'test',
                flavor: values[:flavor],
                build_type: 'release'
            )
    end

    lane :allbetas do
         test( flavor: 'Flavor1')
         flavor1Beta
         test( flavor: 'Flavor2')
         flavor2Beta

         successSlack("HEYYYYOOOOOO")
    end

    lane :allReleases do
         test( flavor: 'Flavor1')
         flavor1Supply
         test( flavor: 'Flavor2')
         flavor2Supply
         successSlack("HEYYYYOOOOOO")
    end


    lane :successSlack do |values|
        slack(
            message: values[:message],
            success: true,
            default_payloads: [:lane],
            payload: {"Platform" => "Android",
                      "Date" => Time.new.to_s}
              )
    end


    error do |lane, exception|
        slack(
            message: exception.to_s,
            success: false,
            default_payloads: [:lane],
            payload: {"Platform" => "Android",
            "Date" => Time.new.to_s}
        )
    end
